# Generated by Django 3.2.7 on 2021-09-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='humidity',
            new_name='api_hum',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='temperature',
            new_name='api_tem',
        ),
        migrations.AddField(
            model_name='board',
            name='real_hum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='real_tem',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
