# Generated by Django 3.2.7 on 2021-09-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20210925_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='writer',
            field=models.CharField(default='admin', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='location',
            field=models.CharField(max_length=10),
        ),
    ]
