# Generated by Django 3.2.7 on 2021-09-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20210925_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='GisangGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si', models.CharField(max_length=20)),
                ('gu', models.CharField(default='default', max_length=20)),
                ('do', models.CharField(default='default', max_length=20)),
                ('gridx', models.IntegerField()),
                ('gridy', models.IntegerField()),
            ],
        ),
    ]
